// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "rust-nostr-nostr-sdk-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNostrSdkReactNativeSpec.h"

@interface NostrSdkReactNative : NSObject <NativeNostrSdkReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface NostrSdkReactNative : NSObject <RCTBridgeModule>
#endif

@end