name: Generate
description: Set up dependencies and regenerate the bindings

inputs:
  platform:
    description: One of android, ios
    required: true
  release:
    description: Whether to build in release mode, one of true, false
    default: "false"

runs:
  using: composite
  steps:
      - name: Setup JS
        uses: ./.github/actions/setup-js

      - name: Install cargo-ndk
        if: ${{ inputs.platform == 'android' }}
        shell: bash
        run: cargo install cargo-ndk

      - name: Install clang-format
        if: ${{ inputs.platform == 'ios' }}
        shell: bash
        run: brew install clang-format

      - name: Write .xcode.env.local
        if: ${{ inputs.platform == 'ios' }}
        shell: bash
        run: |
          # Work around for https://github.com/facebook/react-native/issues/35657
          echo "export NODE_BINARY=$(which node)" >> example/ios/.xcode.env.local
          cat example/ios/.xcode.env.local

      - name: Generate
        shell: bash
        env:
          PLAT: ${{ inputs.platform == 'android' && 'android' || 'ios' }}
          MODE: ${{ inputs.release == 'true' && '--release' || '' }}
        run:
          yarn ubrn:$PLAT $MODE

      - name: Check if repository is dirty
        shell: bash
        env:
          EXCLUDE: ${{ inputs.platform == 'android' && 'ios' || 'android' }}
        run: |
          if [[ -n "$(git status --porcelain | grep -v ". $EXCLUDE" | grep -v example/ios/Podfile.lock)" ]]; then
            >&2 echo "Found unexpected changes in repository after generating"
            git status --short
            git diff
            exit 1
          fi
